# Generated by Django 4.2.2 on 2023-06-15 16:36

from django.db import migrations, models
import pictopia.post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts', validators=[pictopia.post.validators.image_size_validation]),
        ),
    ]
